version: '2'

services:

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - 9010:9000
    volumes:
      - ./:/var/www/app/
      - ./php.ini:/usr/local/etc/php/php.ini
