services:

  php-fpm74:
    build:
      context: .
      dockerfile: phpfpm7.4.Dockerfile
    user: www-data:www-data
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/log/:/var/log/fpm-php/
      - ./.config:/root/.config
      - ./.config/.zshrc:/root/.zshrc
      - ./.config:/var/www/.config
      - ./.config/.zshrc:/var/www/.zshrc
    networks:
      - app-network

  httpd74:
    image: httpd:alpine
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/conf/sites/vhosts74.conf/:/usr/local/apache2/conf/sites/vhosts74.conf
    ports:
      - 9074:80

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
