services:

  php-fpm56:
    build:
      context: .
      dockerfile: phpfpm5.6.Dockerfile
    user: www-data:www-data
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./php-fpm/log/:/var/log/fpm-php/
      - ./.config:/root/.config
      - ./.config/.zshrc:/root/.zshrc
      - ./.config:/var/www/.config
      - ./.config/.zshrc:/var/www/.zshrc
    networks:
      - app-network56

  httpd56:
    image: httpd:alpine
    volumes:
      - ${LOCAL_DIR}:/var/www/
      - ./apache2/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache2/conf/sites/vhosts56.conf/:/usr/local/apache2/conf/sites/vhosts56.conf
    ports:
      - 9056:80

    networks:
      - app-network56

networks:
  app-network56:
    driver: bridge
